name: ci
 
on:
 push:
   branches: main
 
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - uses: actions/checkout@v2
     -
       name: Build and push iam-service-login
       uses: docker/build-push-action@v2
       with:
         context: ./
         file: ./Dockerfile.binary
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipslabs/iam-service-login:latest
         cache-from: type=registry,ref=philipslabs/iam-service-login:latest
         cache-to: type=inline
